accounts/urls.py
from django.contrib import admin
from django.urls import reverse_lazy, path
from .views import *
admin.autodiscover()

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('profile',Profile_view, name='view_profile'),
    path('edit-profile', EditUser.as_view(), name='edit_profile'),
    path('change-password', PasswordChange.as_view(), name='Password_Change'),

    
]

balancechecker/urls.py
from django.urls import path
from .views import *


app_name = 'balance_checker'


urlpatterns = [
    path('', IndexView.as_view(), name="check_index"),
    path('vouchers/<int:id>', OrderVouchersView.as_view(), name="order_vouchers"),
    path('upload-vouchers', UploadCSV.as_view(), name="upload_vouchers"),
    path('download-order-voucher', DownloadOrderVoucher.as_view(), name='download_order_voucher'),
    path('start-order-process/<int:id>', StartOrderProcess.as_view(), name='start_order_process'),
    path('stop-order-process/<int:id>', StopOrderProcess.as_view(), name='stop_order_process'),

    path('api/get-data/', get_data, name='get_data'),
]

core/urls.py
from django.urls import path
from .views import checkbal_view
urlpatterns = [
    path('', checkbal_view)
]

frontend/urls.py
from django.contrib import admin
from django.urls import reverse_lazy, path
from .views import *
from .sitemaps import *
# from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static


app_name = 'frontend'

# sitemaps = {
#  'pages': StaticSitemap,
# }


urlpatterns = [
    path('', index, name='index'),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # path('robots.txt', robot, name='robots'),
    # path('robots/',robot, name='robots'),
    path('about',about_us, name='about_us_page'),
    path('services',services, name='services_page'),
    path('gift-cards',gift_cards, name='gift_cards'),
    path('contact',contact_us, name='contact_us_page'),
    
    
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from .views import *
from django.urls import path

app_name = 'market'

urlpatterns = [
    path('category', PanelView.as_view(), name='panels_view'),
    path('category-records/<int:pk>', CategoryRecordsView.as_view(), name='category_records'),
    path('download-category-records/<int:pk>', DownloadCategoryRecordsView.as_view(), name='download_category_records'),
    path('delete-category/<int:pk>', DeletePanelView.as_view(), name='delete_category'),
    path('delete-record/<int:pk>', DeleteRecordView.as_view(), name='delete_record'),
    path('edit-record/<int:pk>', EditRecordView.as_view(), name='edit_record'),
    
    path('records', RecordView.as_view(), name='record_page'),
    path('add-new-entry', AddRecordView.as_view(), name='add_user_record'),
    path('upload-records', RecordUploadView.as_view(), name='upload_records'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    
    
]

templates/admin-includes/footer.html
{% load static %}

<!-- partial:../../partials/_footer.html -->
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © <script>document.write(/\d{4}/.exec(Date())[0])</script>
          . CredenceRewards <a
                href="https://credencerewards.com" target="_blank">CredenceRewards</a>
            All rights reserved.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Develpoped and Designed by CredenceRewards Team
           
    </div>
</footer>
<!-- partial -->
</div>
<!-- main-panel ends -->
</div>
<!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<script src="{% static 'assets/jquery.min.js' %}"></script>

<script>
  // show alert message for notification

  function showSnackbar() {
    var snackBar =
      document.getElementById("snackbar")
    snackBar.className = "show-bar";

    setTimeout(function () {
      snackBar.className =
        snackBar.className.replace("show-bar", "show-error");
    }, 5000);
  }

</script>
{% if messages %}
{% for message in messages %}
{% if message.tags == "error" %}
<script>
  showSnackbar();
  $('#snackbar').css("cssText", "background-color: red !important;");
  $('#snackbar').text("{{ message|safe }}");
</script>
{% else %}
<script>
  showSnackbar();
  $('#snackbar').css("cssText", "background-color: green !important;");
  $('#snackbar').text("{{ message|safe }}");
</script>
{% endif %}
{% endfor %}
{% endif %}

<!-- js -->
<script>
    $(document).on('click', '.custom-clickable-row', function (e) {
        var url = $(this).data('href');
        window.location = url;
    });
</script>

<!-- plugins:js -->
<script src="{% static 'admin-asset/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{% static 'admin-asset/vendors/chart.js/Chart.min.js' %}"></script>

<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static 'admin-asset/js/off-canvas.js' %}"></script>
<script src="{% static 'admin-asset/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'admin-asset/js/template.js' %}"></script>
<script src="{% static 'admin-asset/js/settings.js' %}"></script>
<script src="{% static 'admin-asset/js/todolist.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{% static 'admin-asset/js/dashboard.js' %}"></script>
<script src="{% static 'admin-asset/js/Chart.roundedBarCharts.js' %}"></script>
<!-- End custom js for this page-->
</body>

</html>

templates/admin-includes/header.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin-CredenceRewards</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'admin-asset/vendors/feather/feather.css' %}">
    <link rel="stylesheet" href="{% static 'admin-asset/vendors/ti-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'admin-asset/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{% static 'admin-asset/vendors/ti-icons/css/themify-icons.css' %}">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'admin-asset/css/vertical-layout-light/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'assets/images/cr-images/favicon.png' %}" />
</head>
<style>
    .navbar .navbar-brand-wrapper .navbar-brand img {
        max-width: 100%;
        height: 51px;
        margin: auto;
        margin-left: 30px;
        vertical-align: middle;
    }
</style>

<body >
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row navbar-success">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center bg-success">
                <a class="navbar-brand brand-logo mr-5" href="/">
                    <img src="{% static 'admin-asset/images/Credence_Rewards_logo.png' %}" class="mr-2" width="" height="240px" alt="logo" /></a>
                <a class="navbar-brand brand-logo-mini" href="/">
                    <img src="{% static 'admin-asset/images/Credence_Rewards_logo.png' %}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>
                {% if request.user.is_superuser %}

                <ul class="navbar-nav mr-lg-2 row">
                    <li class="nav-item nav-search d-none d-lg-block">
                        <div class="input-group">
                            <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                                <span class="input-group-text" id="search">
                                    <i class="icon-search"></i>
                                </span>
                            </div>
                            <form id="search-form" action="" method="get">
                                <input type="search" class="form-control " style="width:400px" autocomplete="off" value="{{ query }}" id="navbar-search-input" placeholder="Search now"
                                    aria-label="search" name="q" aria-describedby="search">
                            </form>
                            <span class="small p-2 text-white">Sarch Date as (YYYY-MM-DD)<br> E.g - <u>2023-04-15</u></span>
                        </div>
                    </li>
                </ul>
                {% else %}
                <div class="navbar-nav mr-lg-2 text-center row">
                    <span class="">

                        <h3 class="nav-item nav-search  text-light d-none d-lg-block">
                            Marketting Panel Credencerewards
                        </h3>
                    </span>
                </div>
                {% endif %}
                <ul class="navbar-nav navbar-nav-right">
                    
                    {% if not request.user.is_superuser %}
                    <li class="nav-item">
                            <a class="me-3 hidden-arrow" href="#" 
                            >
                                <i class="ti-bell text-warning icon-md"></i>
                                <span class="badge rounded-pill badge-notification bg-white ">1</span>
                            </a>
                   
                    </li><!-- End Notification Nav -->
                    {% endif %}
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                            <img src="{% static 'admin-asset/images/images.png' %}" alt="profile" />
                            {% if request.user.is_superuser %}
                             Admin
                             {% else %}
                             Staff
                             {% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown"
                            aria-labelledby="profileDropdown">
                            <a class="dropdown-item">
                                <i class="ti-settings text-primary"></i>
                                Settings
                            </a>
                            <a href="/admin/accounts/user/" class="dropdown-item">
                                <i class="icon-ellipsis"></i>
                                Django Panel
                            </a>
                            <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                                <i class="ti-power-off text-primary"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                    <!-- <li class="nav-item nav-settings d-none d-lg-flex">
                        <a class="nav-link" href="#">
                            <i class="icon-ellipsis"></i>
                        </a>
                    </li> -->
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                    data-toggle="offcanvas">
                    <span class="icon-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
   
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas bg-success text-white" id="sidebar">
                <ul class="nav">
                        <li class="nav-item ">
                            <a class="nav-link" href="{% url 'frontend:index' %}">
                                <i class="icon-layout menu-icon"></i>
                                <span class="menu-title">Dashboard</span>
                            </a>
                        </li>
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'balance_checker:check_index' %}">
                                <i class="icon-grid menu-icon"></i>
                                <span class="menu-title">Balance Checker</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if status == 'panels' %}active{% endif %}" href="{% url 'market:panels_view' %}">
                                <i class="icon-grid menu-icon"></i>
                                <span class="menu-title">Panels</span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link {% if status == 'all_records' %}active{% endif %}" href="{% url 'market:record_page' %}">
                                <i class="icon-record menu-icon"></i>
                                <span class="menu-title">Records</span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link {% if status == 'add_record' %}active{% endif %}" href="{% url 'market:add_user_record' %}">
                                <i class="icon-plus menu-icon"></i>
                                <span class="menu-title">Add Record</span>
                            </a>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link {% if status == 'notifications' %}active{% endif %}" href="{% url 'market:notifications' %}">
                                <i class="icon-bell menu-icon"></i>
                                <span class="menu-title">Notifications</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            <div id="snackbar" class="show-error">
      
            </div>
            <div class="main-panel">