balancechecker/urls.py
from django.urls import path
from .views import *


app_name = 'balance_checker'


urlpatterns = [
    path('', IndexView.as_view(), name="check_index"),
    path('vouchers/<int:id>', OrderVouchersView.as_view(), name="order_vouchers"),
    path('upload-vouchers', UploadCSV.as_view(), name="upload_vouchers"),
    path('download-order-voucher', DownloadOrderVoucher.as_view(), name='download_order_voucher'),
    path('start-order-process/<int:id>', StartOrderProcess.as_view(), name='start_order_process'),
    path('stop-order-process/<int:id>', StopOrderProcess.as_view(), name='stop_order_process'),

    path('api/get-data/', get_data, name='get_data'),
]

core/urls.py
from django.urls import path
from .views import checkbal_view
urlpatterns = [
    path('', checkbal_view)
]

templates/check-balance/orders.html
{% include "admin-includes/header.html" %}
{% block content %}
{% load static %}
{% load extras %}
<style>
	
	.pagination a {
	  color: black;
	  float: left;
	  border-radius: 5px;
	  transition: background-color .3s;
	  border: 1px solid #ddd; /* Gray */
	  margin: 0 4px; /* 0 is for top and bottom. Feel free to change it */
	  font-size: 11px;

	  padding: 4px 6px;
	  background:lightgray;
	  text-decoration: none;
	}
	.pagination .active{
	  background-color: lightgreen !important;
	  color: white !important;
			  font-size: 11px !important;
			  padding: 4px 6px !important;
			  border-radius: 5px;
	}
	.pagination a.active {
	  margin-top:15px !important;
	  background-color: lightgreen !important;
	  color: white !important;
	  font-size: 16px !important;
	  padding: 4px 	6px !important;
	  border-radius: 5px;
	}
	.pagination a:hover:not(.active) {
	  background-color: darkgray;
  }

</style>
<!-- partial -->
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<h4 class="card-title">Check Balance Order/Tasks
						<!-- Button trigger modal -->
						<button type="button" class="btn btn-outline-primary bg-light border  p-2 mr-2 float-right"
							data-toggle="modal" data-target="#Upload-Vouchers-Modal">
							<i class="ti-upload text-dark mr-2 ml-1"></i> <b>Upload</b>
						</button>
					</h4>
					<p class="card-description">
						Orders
					</p>
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<thead>
								<tr>
									<th>Order_id</th>
									<th>Remark</th>
									<th>Vouchers</th>
									<th>Total Data Vouchers</th>
									<th>Created On</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								{% if orders %}
								{% for order in orders %}
								<tr style="cursor:pointer;" class="custom-clickable-row font-weight-bold"
									data-href="{% url 'balance_checker:order_vouchers' order.id %}">
									<td>{{ order.id }}</td>
									<td> {{ order.user_remark|default_if_none:"--" }} </td>
									<td> {{ order.total_vouchers }} </td>
									<td>{{ order.order_voucher.all|length }}</td>
									<td> {{ order.created_on.date }} </td>
									<td class="text-center">
										{{ order.id|order_status|safe }}
										{% comment %} <div class="progress">5%
											<div class="progress-bar bg-danger" role="progressbar" style="width: 5%"
												aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
										</div>
										<div class="progress">
											<div class="progress-bar bg-primary" role="progressbar" style="width: 60%"
												aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">60%</div>
										</div> {% endcomment %}
										
									</td>
								</tr>
								{% endfor %}
								{% else %}
								<tr>
									<td align="center" colspan="6">No order Found to display</td>
								</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					{% if orders.has_other_pages %}
						<div class="col d-flex justify-content-center mt-2">
							<ul class="pagination">
								{% if orders.has_previous %}
								<li><a href="?page={{ orders.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">&laquo;</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span>
								</li>
								{% endif %}
								{% if orders.number|add:'-9' > 1 %}
								<li><a href="?page={{ orders.number|add:'-9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								{% endif %}
								{% for i in orders.paginator.page_range %}
								{% if orders.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
								{% elif i > orders.number|add:'-8' and i < orders.number|add:'8' %}
								<li><a href="?page={{ i }}{% if query %}&q={{ query }}{% endif %}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if orders.paginator.num_pages > orders.number|add:'9' %}
								<li><a href="?page={{ orders.number|add:'9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								<li><a href="?page={{ last_page }}{% if query %}&q={{ query }}{% endif %}">Last</a></li>
								{% endif %}

								{% if orders.has_next %}
								<li><a href="?page={{ orders.next_page_number }}{% if query %}&q={{ query }}{% endif %}">&raquo;</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span>
								</li>
								{% endif %}
							</ul>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
<!-- content-wrapper ends -->

<!-- upload modal -->
<!-- Modal -->
<div class="modal fade" id="Upload-Vouchers-Modal" tabindex="-1" role="dialog" aria-labelledby="UploadVouchersModal"
	aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered rounded" role="document">
		<div class="modal-content ">

			<div class="modal-header bg-info">
				<h5 class="modal-title " id="Upload-Vouchers-ModalTitle">Upload Excel File</h5>
				<button type=" button" class="close btn btn-danger bg-danger text-white" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form id="upload-form" onsubmit="return checkfile(this.file);" action="{% url 'balance_checker:upload_vouchers' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
			<div class="modal-body">
				<div class="row mt-0">
					<div class="col-12 text-center text-secondary">
						<i>Note: 	
						How to upload excel file ? </i>
						<a class="ml-2 border" href="{% static 'admin-asset/example/excel-desired-upload-format.xlsx' %}"> Download Format</a>
					</div>
					<div class="col-12 small py-2 text-center text-primary">
						10000 (10k) recods are able to be uploaded per upload. It is good to upload on daily basis and check for daily reports. 
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-12 col-form-label m-0">Enter Remark for your Order <small class="ml-4 text-warning">Help text of your Upload</small></label>
					<div class="col-sm-12">
					  <input type="text" maxlength="20"  name="remark" class="form-control" />
					</div>
				  </div>
				<div class="form-group">
					<label>Select Excel File to Upload</label>
					<input type="file" name="expfile" id="excel-file" accept=".xls,.xlsx" required class="file-upload-default">
					<div class="input-group col-xs-12">
						<input type="text" class="form-control file-upload-info"  disabled placeholder="Upload Image">
						<span class="input-group-append">
							<button class="file-upload-browse btn btn-info" type="button">Choose</button>
						</span>
					</div>
				</div>
				<div class="modal-footer border border-0 align-self-center">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-success">Upload</button>
				</div>
			</div>
		</form>
		</div>
	</div>
</div>
<!-- endupload modal -->
<script src="{% static 'assets/jquery.min.js' %}"></script>
<script src="{% static 'admin-asset/js/file-upload.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/jquery-validate.js' %}">
</script>
<script type="text/javascript">

$(document).ready(function() {
	$('#search-form').attr('action' , "{% url 'balance_checker:check_index' %}");
});


$("#upload-form").validate({
	rules: {
		expfile: {
			required: true,
		},
	},
	messages: {
		expfile: {
			required: "Select file to upload",

		},
	}
});

</script>
<script>
    function checkfile(sender) {
        var validExts = [".xlsx", ".xls"];
        var fileExt = sender.value;
        fileExt = fileExt.substring(fileExt.lastIndexOf('.'));
        if (validExts.indexOf(fileExt) < 0) {
            alert("Invalid file selected, valid files are of " +
                validExts.toString() + " types.");
            //document.getElementById("excel-file").value=' ';
            return false;
        } else return true;
    }
</script>
{% endblock %}
{% include "admin-includes/footer.html" %}

templates/check-balance/vouchers.html
{% include "admin-includes/header.html" %}
{% block content %}
{% load static %}
{% load extras %}
<style>
	  .pagination a {
		color: black;
		float: left;
		border-radius: 5px;
		transition: background-color .3s;
		border: 1px solid #ddd; /* Gray */
		margin: 0 4px; /* 0 is for top and bottom. Feel free to change it */
		font-size: 11px;

		padding: 4px 6px;
		background:lightgray;
		text-decoration: none;
	  }
	  .pagination .active{
		background-color: lightgreen !important;
		color: white !important;
				font-size: 11px !important;
				padding: 4px 6px !important;
				border-radius: 5px;
	  }
	  .pagination a.active {
		margin-top:15px !important;
		background-color: lightgreen !important;
		color: white !important;
		font-size: 16px !important;
		padding: 4px 	6px !important;
		border-radius: 5px;
	  }
	  .pagination a:hover:not(.active) {
		background-color: darkgray;
	}

</style>
<!-- partial -->
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<h4 class="card-title">Check Balance Order/Tasks
					<!-- Button trigger modal -->
					<span class="float-right">
						{% if order.is_started  %}
						<a href="{% url 'balance_checker:stop_order_process' id %}" 
							onclick="return confirm('Are you sure you want to stop this Order, You can Start this later?');"
							class="btn btn-outline-success bg-light border  p-2 mr-2 ">
						<i class="ti-arrow-left text-dark mr-2 ml-1"></i> <b>Stop Process</b>
						</a>
						{% else %}
						<a href="{% url 'balance_checker:start_order_process' id %}" 
							onclick="return confirm('Are you sure you want to start this Order, You can Stop this later?');"
							class="btn btn-outline-success bg-light border  p-2 mr-2 ">
						<i class="ti-arrow-right text-dark mr-2 ml-1"></i> <b>Start Process</b>
						</a>
						{% endif %}
						<a data-toggle="modal" data-target="#Upload-Vouchers-Modal"
							class="btn btn-outline-success bg-light border  p-2 mr-2 ">
							<i class="ti-download text-danger mr-2 ml-1"></i> <b>Download</b>
						</a>
					</span>
					</h4>
					<p class="card-description text-center">
						<span class="float-left">Vouchers</span> 
						<span class="mx-5 text-primary font-weight-bold align-items-end">Vouchers Per Page - {{page_count}}</span>
					</p>
					<p class="card-description text-center border px-3">
						<span class="float-left text-success">Checked Vouchers - {{ checked_vouchers }}</span> 
						<span class=" text-primary">Amount - {{ total_amount }} <small class="text-muted">(Purchased only)</small></span> 
						<span class="mx-5 float-right text-warning font-weight-bold align-items-end">Un-Checked Vouchers - {{ unchecked_vouchers }}</span>
					</p>
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<thead>
								<tr>
									<th>Id</th>
									<th>Code</th>
									<th>Pin</th>
									<th>Balance</th>
									<th class="text-center">Exp</th>
									<th>Error Message</th>
									<th>Checked On</th>
									<th>IsRedeemed</th>
									<th>Status</th>
								</tr>
							</thead>
							<tbody>
								{% if vouchers %}
								{% for voucher in vouchers %}
								<tr>
									<td>{{ voucher.id }}</td>
									<td class="px-0 text-primary">{{ voucher.code }}</td>
									<td class="px-1 text-primary"> {{ voucher.pin }} </td>
									<td class="px-0 text-success text-center"> {{ voucher.balance }} </td>
									<td class="px-0 text-center"> {{ voucher.expiry }} </td>
									<td class="text-center" style=" width: 10% !important;white-space:pre-wrap; word-wrap:break-word;font-size:9px;padding:0px;"> {{ voucher.message }} </td>
									<td class="px-0 text-center" style="font-size:11px;"><small> {{ voucher.responsed_on.date }} <br> {{ voucher.responsed_on.time }}</small> </td>
									<td>
										{% if voucher.is_checked %}

											{% if voucher.status == 1 %}
											<label class="badge badge-info">
												Purchased
											</label>
											{% elif voucher.status == 2 %}
											<label class="badge badge-warning">
												Activated
											</label>
											{% else %}
											<label class="badge badge-primary">
												Not Known
											</label>
											{% endif %}

										{% else %}
										<label class="badge badge-secondary">Not Checked</label>
										{% endif %}
										</td>
									<td>
                                    {% if voucher.is_checked %}
                                    <label class="badge badge-success">Checked</label>
                                    {% else %}
                                    <label class="badge badge-warning">Not Checked</label>
                                    {% endif %}
                                    </td>
								</tr>
								{% endfor %}
								{% else %}
								<tr>
									<td align="center" colspan="6">No order Found to display</td>
								</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					{% if vouchers.has_other_pages %}
					<div class="col d-flex justify-content-center mt-2">
						<ul class="pagination">
								{% if vouchers.has_previous %}
								<li><a href="?page={{ vouchers.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">&laquo;</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span>
								</li>
								{% endif %}
								{% if vouchers.number|add:'-9' > 1 %}
								<li><a href="?page={{ vouchers.number|add:'-9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								{% endif %}
								{% for i in vouchers.paginator.page_range %}
								{% if vouchers.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
								{% elif i > vouchers.number|add:'-8' and i < vouchers.number|add:'8' %}
								<li><a href="?page={{ i }}{% if query %}&q={{ query }}{% endif %}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if vouchers.paginator.num_pages > vouchers.number|add:'9' %}
								<li><a href="?page={{ vouchers.number|add:'9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								<li><a href="?page={{ last_page }}{% if query %}&q={{ query }}{% endif %}">Last</a></li>
								{% endif %}

								{% if vouchers.has_next %}
								<li><a href="?page={{ vouchers.next_page_number }}{% if query %}&q={{ query }}{% endif %}">&raquo;</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span>
								</li>
								{% endif %}
							</ul>
						</div>
						{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
<!-- content-wrapper ends -->

<!-- upload modal -->
<!-- Modal -->
<div class="modal fade" id="Upload-Vouchers-Modal" tabindex="-1" role="dialog" aria-labelledby="UploadVouchersModal"
	aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered rounded" role="document">
		<div class="modal-content ">

			<div class="modal-header bg-info">
				<h5 class="modal-title " id="Upload-Vouchers-ModalTitle">Download Excel File</h5>
				<button type=" button" class="close btn btn-danger bg-danger text-white" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form id="upload-form" action="{% url 'balance_checker:download_order_voucher' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
			<div class="modal-body">
				<div class="row mt-0 py-0">
					<div class="col-12 mt-0 pt-0 text-center text-secondary">
						<i>Fill criteria to download Excel file or you can directly Download. </i>
					</div>
				</div>
				<input type="hidden" value="{{id}}" name="order_id">
				<div class="form-group pb-0 mb-0 row">
					<label class="col-sm-12 col-form-label m-0">Expiry From</label>
					<div class="col-sm-12">
					  <input type="date"   name="expiryfrom" class="form-control" />
					</div>
				</div>
				<div class="form-group pb-0 mb-0 row">
					<label class="col-sm-12 col-form-label m-0">Expiry to</label>
					<div class="col-sm-12">
					  <input type="date"   name="expiryto" class="form-control" />
					</div>
				</div>
				<div class="form-group border mt-2 px-3 row">
					<div class="form-check px-3 col-4">
						<input class="form-check-input" type="radio" name="checked" value="1" id="flexRadioDefault1" checked>
						<label class="form-check-label" for="flexRadioDefault1">
							Both
						</label>
					</div>
					<div class="form-check px-3 col-4">
						<input class="form-check-input" type="radio" name="checked" value="2" id="flexRadioDefault2">
						<label class="form-check-label" for="flexRadioDefault1">
							Checked
						</label>
					</div>
					<div class="form-check px-3 col-4">
						<input class="form-check-input" type="radio" name="checked" value="3" id="flexRadioDefault3" >
						<label class="form-check-label" for="flexRadioDefault2">
							Not Checked
						</label>
					</div>
				</div>
				<div class="modal-footer border border-0 align-self-center">
					<button type="button" class="btn btn-secondary " data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-success">Download</button>
				</div>
			</div>
		</form>
		</div>
	</div>
</div>
<!-- endupload modal -->
<script>
	$(document).ready(function() {
		$('#search-form').attr('action' , "{% url 'balance_checker:order_vouchers' order.id %}");
	});
</script>

{% endblock %}
{% include "admin-includes/footer.html" %}