balancechecker/urls.py
from django.urls import path
from .views import *


app_name = 'balance_checker'


urlpatterns = [
    path('', IndexView.as_view(), name="check_index"),
    path('vouchers/<int:id>', OrderVouchersView.as_view(), name="order_vouchers"),
    path('upload-vouchers', UploadCSV.as_view(), name="upload_vouchers"),
    path('download-order-voucher', DownloadOrderVoucher.as_view(), name='download_order_voucher'),
    path('start-order-process/<int:id>', StartOrderProcess.as_view(), name='start_order_process'),
    path('stop-order-process/<int:id>', StopOrderProcess.as_view(), name='stop_order_process'),

    path('api/get-data/', get_data, name='get_data'),
]

core/urls.py
from django.urls import path
from .views import checkbal_view
urlpatterns = [
    path('', checkbal_view)
]

market/urls.py
from .views import *
from django.urls import path

app_name = 'market'

urlpatterns = [
    path('category', PanelView.as_view(), name='panels_view'),
    path('category-records/<int:pk>', CategoryRecordsView.as_view(), name='category_records'),
    path('download-category-records/<int:pk>', DownloadCategoryRecordsView.as_view(), name='download_category_records'),
    path('delete-category/<int:pk>', DeletePanelView.as_view(), name='delete_category'),
    path('delete-record/<int:pk>', DeleteRecordView.as_view(), name='delete_record'),
    path('edit-record/<int:pk>', EditRecordView.as_view(), name='edit_record'),
    
    path('records', RecordView.as_view(), name='record_page'),
    path('add-new-entry', AddRecordView.as_view(), name='add_user_record'),
    path('upload-records', RecordUploadView.as_view(), name='upload_records'),
    path('notifications', NotificationsView.as_view(), name='notifications'),
    
    
]

market/models.py
from django.db import models
from django.core.validators import RegexValidator

number = RegexValidator(
    r'^^(\+\d{1,3})?,?\s?\d{8,13}', 'Only numbers are allowed.')
class Source(models.Model):
    title       = models.CharField(max_length=100, null=True, blank=False)
    remark      = models.CharField(max_length=200, null=True, blank=False)
    is_active   = models.BooleanField(default=True)
    created_by  = models.ForeignKey("accounts.User",related_name="category",on_delete=models.DO_NOTHING)
    created_on  = models.DateTimeField(auto_now_add=True, null=True)
    updated_on  = models.DateTimeField(auto_now=True)

    def _str_(self):
        return self.title

class Record(models.Model):
    name            = models.CharField(max_length=300, blank=True, null=True)
    email           = models.CharField(max_length=500, blank=True, null=True)
    mobile_no       = models.CharField(max_length=30, null=True, blank=True)

    remark          = models.CharField(max_length=50, blank=True, null=True)
    is_active       = models.BooleanField(default=True)
    source          = models.ForeignKey(Source,related_name="records",on_delete=models.DO_NOTHING)
    created_by      = models.ForeignKey("accounts.User",null=True,blank=True,related_name="user_record",on_delete=models.DO_NOTHING)

    created_on      = models.DateTimeField(auto_now_add=True)
    updated_on      = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']


class Notification(models.Model):
    title           = models.CharField(max_length=100, blank=True, null=True)
    message         = models.TextField(null=True,blank=True)
    is_critical     = models.BooleanField(default=False)
    is_read         = models.BooleanField(default=False)
    created_on      = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-id']

market/views.py
import os
import csv
import logging
import requests
import pandas as pd
from .models import *
from tablib import Dataset
from accounts.models import *
from django.db.models import Q
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import View
from datetime import datetime, timedelta
from .serializers import SourceSerializer
from project.super_user import staff_required
from .tasks import create_records_from_dataframe
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .scheduler import scheduler

db_logger = logging.getLogger('db')

@staff_required()
class PanelView(View):
    def get(self, request, *args, **kwargs):
        panels=Source.objects.all().order_by("-id")
        data = SourceSerializer(panels,many=True).data
        return render(request, 'market/panels.html',{"panels":data,"status":"panels"})

    def post(self, request, *args, **kwargs):
        title = request.POST.get("title")
        remark = request.POST.get("remark")
        if not title or not remark:
            messages.error(request, 'Enter title and remark')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        if Source.objects.filter(title__icontains = title):
            messages.error(request, 'Category with same title already exist')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        panel=Source.objects.create(title = title,remark = remark,created_by = request.user)
        Notification.objects.create(title="One new panel added.",
                    message = f"One new panel/category added with name <i>{title}<i>")
        messages.success(request, 'Created Successfully')
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

@staff_required()
class CategoryRecordsView(View): 
    def get(self, request,pk):
        try:
            panel=Source.objects.get(id=pk)
            records = Record.objects.filter(source_id = pk).order_by("-created_on")
            query = ""
            if request.GET.get("q"):
                query = request.GET.get("q")
                try:
                    records=records.filter(Q(id=query)|Q(name__icontains=query)|Q(email__icontains=query)|Q(mobile_no=query),source_id = pk).order_by("-created_on").distinct()
                    if not records:
                        raise
                except:
                    records=records.filter(Q(name__icontains=query)|Q(email__icontains=query)|Q(mobile_no=query),source_id = pk).order_by("-created_on").distinct()
            else:
                records = Record.objects.filter(source_id = pk).order_by("-created_on")

            page = request.GET.get('page', 1)
            paginator = Paginator(records,8)

            try:
                records = paginator.page(page)
            except PageNotAnInteger:
                records = paginator.page(1)
            except EmptyPage:
                records = paginator.page(paginator.num_pages)
            return render(request, 'market/cat-records.html',{"records":records,"query":query,"panel":panel,"status":"all_records"})

        except Exception as e:
            print(e)
            messages.error(request, 'Category not found')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@staff_required()
class RecordView(View):
    def get(self, request, *args, **kwargs):
        query = ""
        if request.GET.get("q"):
            query = request.GET.get("q")
            try:
                records=Record.objects.filter(Q(id=query)|Q(name__icontains=query)|Q(email__icontains=query)|Q(mobile_no=query)).order_by("email","name").distinct()
                if not records:
                    raise
            except:
                records=Record.objects.filter(Q(name__icontains=query)|Q(email__icontains=query)|Q(mobile_no=query)).order_by("email","name").distinct()
        else:
            records=Record.objects.all().order_by("email","name")

        page = request.GET.get('page', 1)
        paginator = Paginator(records,20)

        try:
            records = paginator.page(page)
        except PageNotAnInteger:
            records = paginator.page(1)
        except EmptyPage:
            records = paginator.page(paginator.num_pages)
        return render(request, 'market/records.html',{"records":records,"query":query,"last_page":paginator.num_pages,"status":"all_records"})



@staff_required()
class NotificationsView(View):
    def get(self, request, *args, **kwargs):
       
        notifications=Notification.objects.all().order_by("-created_on")
        page = request.GET.get('page', 1)
        paginator = Paginator(notifications,100)
        try:
            notifications = paginator.page(page)
        except PageNotAnInteger:
            notifications = paginator.page(1)
        except EmptyPage:
            notifications = paginator.page(paginator.num_pages)

        return render(request, 'market/notifications.html',{"notifications":notifications,"status":"notifications"})


@staff_required()
class AddRecordView(View):
    def get(self, request, *args, **kwargs):
        panels=Source.objects.all().order_by("-id")
        return render(request, 'market/add-records.html',{"panels":panels,"status":"add_record"})
    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        email = request.POST.get("email")
        mobile_no = request.POST.get("mobile_no")
        remark = request.POST.get("remark")
        category_id = request.POST.get("category_id")
        print(name,email,category_id)
        if not name or not email or not category_id:
            messages.error(request, 'Enter name and email and category')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        try:
            category = Source.objects.get(id=category_id)
        except:
            messages.error(request, 'User Record with same email already exist')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        
        if Record.objects.filter(mobile_no = mobile_no):
            messages.error(request, 'User Record with same mobile no already exist')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

        if Record.objects.filter(email__iexact = email):
            messages.error(request, 'User Record with same email already exist')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
         
        user=Record.objects.create(
            name = name,
            email = email,
            mobile_no = mobile_no,
            remark = remark,
            source = category,
            created_by=request.user
        )
        Notification.objects.create(title="One recorded added manually",
                            message = f"Record created manually in {category.title} panel")
        messages.success(request, 'Created Successfully')
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))



'''
Upload Excel
'''    
# @csrf_exempt
class RecordUploadView(View):
    def post(self, request):    
        filename = request.FILES.get('expfile')
        category_id = request.POST.get("category_id")
        remark = request.POST.get("remark")
        if not filename:
            messages.success(request, 'File not found')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        try:
            category = Source.objects.get(id=category_id)
        except:
            messages.error(request, 'Category not found')
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        excel_data_df = pd.read_excel(filename)
        scheduler.add_job(create_records_from_dataframe, trigger="date", args=[excel_data_df,remark,category,request.user], run_date=datetime.now() + timedelta(seconds=1))
        Notification.objects.create(title="Excel file recieved",
        message = "Records will create in few minutes.")

        messages.success(request, 'Will be uploaded in few minutes, Please check notification tab for updates.')
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@staff_required()
class DownloadCategoryRecordsView(View):
    def get(self, request,pk):
        try:
            panel=Source.objects.get(id=pk)
            data = panel.records.values_list("id","name","email","mobile_no","remark","source__title","source_id","created_by__full_name","created_on__date")
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = f'attachment; filename=Credencerewards-{panel.title}-user-records.csv'
            csv_writer = csv.writer(response)
            csv_writer.writerow(["RecordId","Name","Email","Mobile_No","Remark","CategoryTitle","categoryId","CreatorName","Dated"])
            csv_writer.writerows(data)
            return response
        except:
            records = Record.objects.all()
            data = records.values_list("id","name","email","mobile_no","remark","source__title","source_id","created_by__full_name","created_on__date")
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename=Credencerewards-all-user-records.csv'
            csv_writer = csv.writer(response)
            csv_writer.writerow(["RecordId","Name","Email","Mobile_No","Remark","CategoryTitle","categoryId","CreatorName","Dated"])
            csv_writer.writerows(data)
            return response


@staff_required()
class DeletePanelView(View):
    def get(self, request,pk):
        try:
            panel=Source.objects.get(id=pk)
            if len(panel.records.all()) == 0:
                panel.delete()
                messages.success(request, "Deleted suucessfully")
            else:
                messages.error(request, "can't delete unempty category")
        except:

templates/market/cat-records.html
{% include "admin-includes/header.html" %}
{% block content %}
{% load static %}
{% load extras %}
<style>
	
	.pagination a {
	  color: black;
	  float: left;
	  border-radius: 5px;
	  transition: background-color .3s;
	  border: 1px solid #ddd; /* Gray */
	  margin: 0 4px; /* 0 is for top and bottom. Feel free to change it */
	  font-size: 11px;

	  padding: 4px 6px;
	  background:lightgray;
	  text-decoration: none;
	}
	.pagination .active{
	  background-color: lightgreen !important;
	  color: white !important;
			  font-size: 11px !important;
			  padding: 4px 6px !important;
			  border-radius: 5px;
	}
	.pagination a.active {
	  margin-top:15px !important;
	  background-color: lightgreen !important;
	  color: white !important;
	  font-size: 16px !important;
	  padding: 4px 	6px !important;
	  border-radius: 5px;
	}
	.pagination a:hover:not(.active) {
	  background-color: darkgray;
  }

</style>
<!-- partial -->
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<h4 class="card-title"><span class="text-primary">{{panel.title}}</span> Records
					<a href="{% url 'market:download_category_records' panel.id %}" class="btn btn-outline-success bg-light border  p-2 mr-2 float-right">
							<i class="ti-download text-success mr-2 ml-1"></i> <b>Download</b>
					</a>
						<a href="{% url 'market:add_user_record' %}" class="btn btn-outline-primary bg-light border  p-2 mr-2 float-right">
							<i class="ti-plus text-dark mr-2 ml-1"></i> <b>Add New</b>
					</a>
					<div class="input-group col-lg-5 float-right py-0 my-0">
						<div class="input-group-prepend hover-cursor" id="navbar-search-icon">
							<span class="input-group-text" id="search">
								<i class="icon-search"></i>
							</span>
						</div>
						<form id="search-form" action="{% url 'market:category_records' panel.id %}" method="get">
							<input type="search" class="form-control py-0 my-0" style="width:400px" autocomplete="off" value="{{ query }}" id="navbar-search-input" placeholder="Search now"
								aria-label="search" name="q" aria-describedby="search">
						</form>
					</div>
					</h4>
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<thead>
								<tr class="text-center">
									<th>Record_Id</th>
									<th>Name</th>
									<th>Email</th>
									<th>Mobile No.</th>
									<th>Source</th>
									<th>Created On</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								{% if records %}
								{% for record in records %}
								<tr>
									<td>#{{ record.id }}</td>
									<td> {{ record.name|default_if_none:"--" }} </td>
									<td> {{ record.email|default_if_none:"--" }} </td>
									<td>{{ record.mobile_no|default_if_none:"--" }}</td>
									<td class="text-center">
										<span class="badge bg-success">{{record.source.title}}</span>
									</td>
									<td> {{ record.created_on.date }} </td>
									<td>
										<div class="d-flex justify-content-between my-0 py-0">
											<a href="{% url 'market:edit_record' record.id %}"
												title="Edit Record"
												class="btn btn-info shadow btn-xs sharp mr-1 my-0 py-1">
												<i class="ti-pencil my-0"></i></a>

												<a title="View Record"
												href="{% url 'market:edit_record' record.id %}"
												 class="btn btn-primary shadow btn-xs sharp mr-1 my-0 py-1">
												<i class="ti-eye my-0"></i></a>

												<a title="Delete Record"
												href="{% url 'market:delete_record' record.id %}"
												onclick="return confirm('Are you sure to delete?')"
												id="update-btn" class="btn btn-danger shadow btn-xs sharp mr-1 my-0 py-1">
												<i class="ti-trash my-0"></i></a>
										</div>
									</td>
								</tr>
								{% endfor %}
								{% else %}
								<tr>
									<td align="center" colspan="6">No order Found to display</td>
								</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					{% if records.has_other_pages %}
						<div class="col d-flex justify-content-center mt-2">
							<ul class="pagination">
								{% if records.has_previous %}
								<li><a href="?page={{ records.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">&laquo;</a></li>
								<li><a href="?page=1{% if query %}&q={{ query }}{% endif %}">First</a></li>

								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span>
								</li>
								{% endif %}
								{% if records.number|add:'-9' > 1 %}
								<li><a href="?page={{ records.number|add:'-9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								{% endif %}
								{% for i in records.paginator.page_range %}
								{% if records.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
								{% elif i > records.number|add:'-8' and i < records.number|add:'8' %}
								<li><a href="?page={{ i }}{% if query %}&q={{ query }}{% endif %}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if records.paginator.num_pages > records.number|add:'9' %}
								<li><a href="?page={{ records.number|add:'9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								<li><a href="?page={{ records.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">Last</a></li>
								{% endif %}

								{% if records.has_next %}
								<li><a href="?page={{ records.next_page_number }}{% if query %}&q={{ query }}{% endif %}">&raquo;</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span>
								</li>
								{% endif %}
							</ul>
						</div>
					{% endif %}
				</div>
				<div class="row d-flex justify-content-end">
					<span class=" mr-5">
						<small>Last Updated On : <strong>{{panel.updated_on}}</strong></small>
					</span>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- content-wrapper ends -->

{% endblock %}
{% include "admin-includes/footer.html" %}

templates/market/panels.html
{% include "admin-includes/header.html" %} {% block content %} {% load static %}
{% load extras %}
<style>
  .stretch-card {
    min-height: 150px;
  }
  .cat-title{
	font-size: larger;
  }
  .horizantal_center {
	text-align: center;
    display: grid;
    align-items: center;
  }
  .content-wrapper{
	padding-top: 20px;
  }
</style>
<div class="content-wrapper">
	<h4 class="text-center mb-3 mt-0 pt-0"><strong> Categories/Sources for records</strong></h4>
  <div class="row mb-4">
	{% if panels %} 
	{% for panel in panels %}
    <div class="col-md-4 mb-3 stretch-card transparent">
      <div class="card card-tale" style="background-color: {{panel.color}};">
        <div class="card-body">
		<p>
			<span>
				<span class="text-secondary">Date</span> : {{ panel.created_on }}</span> 
				<span class="float-right"><span class="text-secondary">Id : </span> {{panel.id}}</span>
		</p>
		<p class="text-center cat-title">{{panel.title}} 			  
		</p>
		<p class="text-center text-light"><small  class="mb-4"><span class="text-secondary">Remark :</span> {{ panel.remark }}</small></p>
		<p class="text-center d-flex justify-content-between">
			<span class="fs-12 mb-2 float-left"><span class="text-secondary">Created By :</span> {{ panel.created_by }}</span>
			<span class="float-right"><span class="text-secondary ">Total Recods</span> : <span>{{panel.records}}</span></span>
		</p>
		<p class="d-flex justify-content-between">
			<a href="{% url 'market:category_records' panel.id %}" title="View Records" class="float-left"><i class="icon-eye mt-0 pt-0 text-white"></i></a>
			<a href="{% url 'market:download_category_records' panel.id %}" title="Download category Records" class="float-left"><i class="icon-download mt-0 pt-0 text-white" ></i></a>
			<a href="{% url 'market:delete_category' panel.id %}" title="Delete Category if empty" class="float-right"><i class="icon-trash mt-0 pt-0 text-white float-right" ></i></a>
		</p>
        </div>
      </div>
    </div>
	{% endfor %} 
	{% else %}
	<p>
		No Panels or source added yet
	</p>
	  {% endif %}
	  <div class="col-md-4 stretch-card transparent">
		<div class="card card-tale" title="Add New Category" >
		  <div class="card-body horizantal_center" title="Add New Category">
			  <button type="button" class="border-0 bg-transparent " title="Add New Category"
			  data-toggle="modal" data-target="#Add-New-Source-Modal">
			  <i class="icon-plus text-white icon-lg" title="Add New Category"></i>
			  </button>
		  </div>
		</div>
	  </div>
  </div>
</div>

<div class="modal fade" id="Add-New-Source-Modal" tabindex="-1" role="dialog" aria-labelledby="UploadVouchersModal"
	aria-hidden="true">
	<div class="modal-dialog  rounded" role="document">
		<div class="modal-content ">

			<div class="modal-header bg-info">
				<h5 class="modal-title " id="Add-New-Source">Add New Panel/Source</h5>
				<button type=" button" class="close btn btn-danger bg-danger text-white" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="" id="add-new-category" method="post">
				{% csrf_token %}
				<div class="modal-body">
				<h6 class="text-center text-info">Add New panel/Category/Source for records</h6>
				<div class="form-group row mb-1">
					<label class="col-sm-12 col-form-label m-0">Enter Title</label>
					<div class="col-sm-12">
					  <input type="text" maxlength="20" minlength="5" required name="title" class="form-control" />
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-12 col-form-label m-0">Enter Remark</label>
					<div class="col-sm-12">
					  <input type="text" maxlength="80" minlength="5" required name="remark" class="form-control" />
					</div>
				</div>
				<div class="modal-footer border border-0 text-center align-self-center">
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<button type="submit" class="btn btn-success">Add</button>
				</div>
			</div>
		</form>
		</div>
	</div>
</div>
<!-- endupload modal -->
{% endblock %} {% include "admin-includes/footer.html" %}
<script src="{% static 'assets/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/jquery-validate.js' %}">
</script>
<script type="text/javascript">
$("#add-new-category").validate({
	rules: {
		title: {
			required: true,
		},
		remark: {
			required: true,

		}
	},
	messages: {
		title: {
			required: "Enter title for new category",

		},
		remark: {
			required: "Enter remark for new category",

		},
	}
});

</script>

templates/market/records.html
{% include "admin-includes/header.html" %}
{% block content %}
{% load static %}
{% load extras %}
<style>
	
	.pagination a {
	  color: black;
	  float: left;
	  border-radius: 5px;
	  transition: background-color .3s;
	  border: 1px solid #ddd; /* Gray */
	  margin: 0 4px; /* 0 is for top and bottom. Feel free to change it */
	  font-size: 11px;

	  padding: 4px 6px;
	  background:lightgray;
	  text-decoration: none;
	}
	.pagination .active{
	  background-color: lightgreen !important;
	  color: white !important;
			  font-size: 11px !important;
			  padding: 4px 6px !important;
			  border-radius: 5px;
	}
	.pagination a.active {
	  margin-top:15px !important;
	  background-color: lightgreen !important;
	  color: white !important;
	  font-size: 16px !important;
	  padding: 4px 	6px !important;
	  border-radius: 5px;
	}
	.pagination a:hover:not(.active) {
	  background-color: darkgray;
  }

</style>
<!-- partial -->
<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<h4 class="card-title">All User Records
						<a href="{% url 'market:download_category_records' 12121212 %}" class="btn btn-outline-success bg-light border  p-2 mr-2 float-right">
							<i class="ti-download text-success mr-2 ml-1"></i> <b>Download</b>
						</a>
						<a href="{% url 'market:add_user_record' %}" class="btn btn-outline-primary bg-light border  p-2 mr-2 float-right">
							<i class="ti-plus text-dark mr-2 ml-1"></i> <b>Add New</b>
						</a>
						<div class="input-group col-lg-5 float-right py-0 my-0">
							<div class="input-group-prepend hover-cursor" id="navbar-search-icon">
								<span class="input-group-text" id="search">
									<i class="icon-search"></i>
								</span>
							</div>
							<form id="search-form" action="{% url 'market:record_page' %}" method="get">
								<input type="search" class="form-control py-0 my-0" style="width:400px" autocomplete="off" value="{{ query }}" id="navbar-search-input" placeholder="Search now"
									aria-label="search" name="q" aria-describedby="search">
							</form>
						</div>
					</h4>
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<thead>
								<tr class="text-center">
									<th>Record_Id</th>
									<th>Name</th>
									<th>Email</th>
									<th>Mobile No.</th>
									<th>Source</th>
									<th>Created On</th>
									<th>Actions</th>
								</tr>
							</thead>
							<tbody>
								{% if records %}
								{% for record in records %}
								<tr>
									<td>#{{ record.id }}</td>
									<td> {{ record.name|default_if_none:"--" }} </td>
									<td> {{ record.email|default_if_none:"--" }} </td>
									<td>{{ record.mobile_no|default_if_none:"--" }}</td>
									<td class="text-center">
										<span class="badge bg-success">{{record.source.title}}</span>
									</td>
									<td> {{ record.created_on.date }} </td>
									<td>
										<div class="d-flex justify-content-between my-0 py-0">
											<a href="{% url 'market:edit_record' record.id %}"
												title="Edit Record"
												class="btn btn-info shadow btn-xs sharp mr-1 my-0 py-1">
												<i class="ti-pencil my-0"></i></a>

												<a title="View Record"
												href="{% url 'market:edit_record' record.id %}"
												 class="btn btn-primary shadow btn-xs sharp mr-1 my-0 py-1">
												<i class="ti-eye my-0"></i></a>

												<a title="Delete Record"
												href="{% url 'market:delete_record' record.id %}"
												onclick="return confirm('Are you sure to delete?')"
												id="update-btn" class="btn btn-danger shadow btn-xs sharp mr-1 my-0 py-1">
												<i class="ti-trash my-0"></i></a>
										</div>
									</td>
								</tr>
								{% endfor %}
								{% else %}
								<tr>
									<td align="center" colspan="6">No order Found to display</td>
								</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					{% if records.has_other_pages %}
						<div class="col d-flex justify-content-center mt-2">
							<ul class="pagination">
								{% if records.has_previous %}
								<li><a href="?page={{ records.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">&laquo;</a></li>
								<li><a href="?page=1{% if query %}&q={{ query }}{% endif %}">First</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-left" aria-hidden="true"></i></span>
								</li>
								{% endif %}
								{% if records.number|add:'-9' > 1 %}
								<li><a href="?page={{ records.number|add:'-9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								{% endif %}
								{% for i in records.paginator.page_range %}
								{% if records.number == i %}
								<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
								{% elif i > records.number|add:'-8' and i < records.number|add:'8' %}
								<li><a href="?page={{ i }}{% if query %}&q={{ query }}{% endif %}">{{ i }}</a></li>
								{% endif %}
								{% endfor %}
								{% if records.paginator.num_pages > records.number|add:'9' %}
								<li><a href="?page={{ records.number|add:'9' }}{% if query %}&q={{ query }}{% endif %}">&hellip;</a></li>
								<li><a href="?page={{ records.paginator.num_pages }}{% if query %}&q={{ query }}{% endif %}">Last</a></li>
								{% endif %}

								{% if records.has_next %}
								<li><a href="?page={{ records.next_page_number }}{% if query %}&q={{ query }}{% endif %}">&raquo;</a></li>
								{% else %}
								<li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span>
								</li>
								{% endif %}
							</ul>
						</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
<!-- content-wrapper ends -->


{% endblock %}
{% include "admin-includes/footer.html" %}