accounts/urls.py
from django.contrib import admin
from django.urls import reverse_lazy, path
from .views import *
admin.autodiscover()

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('profile',Profile_view, name='view_profile'),
    path('edit-profile', EditUser.as_view(), name='edit_profile'),
    path('change-password', PasswordChange.as_view(), name='Password_Change'),

    
]

core/urls.py
from django.urls import path
from .views import checkbal_view
urlpatterns = [
    path('', checkbal_view)
]

frontend/urls.py
from django.contrib import admin
from django.urls import reverse_lazy, path
from .views import *
from .sitemaps import *
# from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static


app_name = 'frontend'

# sitemaps = {
#  'pages': StaticSitemap,
# }


urlpatterns = [
    path('', index, name='index'),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # path('robots.txt', robot, name='robots'),
    # path('robots/',robot, name='robots'),
    path('about',about_us, name='about_us_page'),
    path('services',services, name='services_page'),
    path('gift-cards',gift_cards, name='gift_cards'),
    path('contact',contact_us, name='contact_us_page'),
    
    
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/views.py
import os
from django.http import HttpResponse
from django.shortcuts import render,redirect
import logging
db_logger = logging.getLogger('db') 



"""
Index Page
"""
def index(request):
    
        if request.user.is_authenticated == True and request.user.is_superuser:
            return redirect('admin:index')
        elif request.user.is_authenticated == True and request.user.is_staff:
            return render(request, "market/index.html", {'status' : 'home'})
        else:
            return render(request, "frontend/index.html", {'status' : 'home'})


def robot(request):
	BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	path= os.path.join(BASE_DIR)
	fin = open(f'{path}/project/robots.txt', 'rb')
	file_content = fin.read()
	fin.close()
	return HttpResponse(file_content, content_type="text/plain")


def about_us(request):
	return render(request, 'frontend/about.html', {'status' : 'about'})
def services(request):
	return render(request, 'frontend/services.html', {'status' : 'services'})

def contact_us(request):
	return render(request, 'frontend/contact.html', {'status' : 'contact'})

def gift_cards(request):
	return render(request, 'frontend/gift-cards.html', {'status' : 'cards'})



"""
error pages
"""

def error_404(request, exception):
    return render(request,'frontend/404.html')
    
def error_500(request):
    db_logger.exception("internal server error")
    return render(request,'frontend/404.html')
    
def error_400(request, exception):
    # db_logger.exception(exception)
    return render(request, 'frontend/404.html', status=404)

templates/frontend/about.html
{% extends './base.html' %}
{% load static %}
{%block content %}

<section data-bs-version="5" class="team1 cid-sz56pECb7o" id="team01-6">
    
    <div class="mbr-overlay"></div>
    <div class="container">
        <div class="mbr-section-head">
            <h4 class="mbr-section-title mbr-fonts-style align-left mb-0 display-7">About Us</h4>
            <h5 class="mbr-section-subtitle mbr-fonts-style align-left mb-0 mt-2 display-5"><strong>CredenceRewards
                </strong><br><strong>Provider for Digital gift cards for everyone. </strong><br></h5>
        </div>
        <div class="row mt-4 justify-content-center">
            <div class="item features-image сol-12 col-md-6 col-lg-4">
                <div class="item-wrapper">
                    <div class="item-img">
                      <img src="{% static 'assets/images/cr-images/login-pic.jpg' %}">
                    </div>
                    <div class="item-content rounded bg-secondary align-left">
                        <h5 class="item-title align-left mbr-fonts-style display-4">Digital gift cards for everyone.</h5>

                        <p class="mbr-text align-left mbr-fonts-style pb-1 display-7"><strong>
                        Pick your card, personalise it and we'll take care of the rest!. Delivered instantly or at your scheduled time by SMS or email
                        </strong></p>
                        <div class="social-row bg-success display-7">
                            <div class="soc-item">
                                 <a href="" target="_blank">
                                    Order Now
                                </a>
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
            <div class="item features-image сol-12 col-md-6 col-lg-4">
                <div class="item-wrapper">
                    <div class="item-img">
                        <img src="{% static 'assets/images/cr-images/login-pic.jpg' %}">
                    </div>
                    <div class="item-content rounded bg-dark align-left">
                        <h5 class="item-title  align-left mbr-fonts-style display-4">eGift cards for every occasion.</h5>

                        <p class="mbr-text align-left mbr-fonts-style pb-1 display-7"><strong>
                        Whatever you're celebrating - a birthday, housewarming, wedding, new baby, anniversary, or just to say, 'Hey, I'm thinking of you!' - we've got just the right eGift! Our eGift cards are the perfect environmentally friendly gift for any occasion.
                        </strong>
                        </p>
                        <div class="social-row bg-info display-7">
                            <div class="soc-item">
                                 <a href="" target="_blank">
                                    Order Now
                                </a>
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
            <div class="item features-image сol-12 col-md-6 col-lg-4">
                <div class="item-wrapper">
                    <div class="item-img">
                      <img src="{% static 'assets/images/cr-images/login-pic.jpg' %}">
                    </div>
                    <div class="item-content rounded bg-primary align-left">
                        <h5 class="item-title align-left mbr-fonts-style display-4">Personalise it!.</h5>

                        <p class="mbr-text align-left mbr-fonts-style pb-1 display-7"><strong>
                        Credence Rewards makes personalised eGifting easier than ever before! Send any Credence Reward eGift Card with a personal message and a greeting card! Get creative and make it a stand-out gift that's meaningful and magical!.

                        </strong>
                        </p>
                        <div class="social-row bg-primary display-7">
                            <div class="soc-item">
                                 <a href="" target="_blank">
                                    Order Now
                                </a>
                            </div>
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section data-bs-version="5" class="numbers1 cid-sz56uYA5zF" id="numbers01-a">



  <div class="container">

      <div class="col-12 m-auto col-lg-8 pb-5">
          <h3 class="mbr-section-title mbr-fonts-style align-left mb-0 display-7">Our History</h3>
          <h5 class="mbr-section-subtitle mbr-fonts-style align-left mb-0 mt-2 display-5"><strong>
              We believe that there’s a perfect gift for everyone, which is why we offer you gift cards from 100+ reputed brands for every gifting occasion. Gift your loved ones the freedom of choice to select a product they truly desire.</strong></h5>
      </div>

      <div class="row">
          <div class="card col-12 col-md-6 col-lg-4">
              <div class="card-wrapper">
                  <div class="card-box align-left">

                      <h5 class="card-title mbr-fonts-style display-2"><strong>2M +</strong></h5>
                      <p class="card-text mbr-fonts-style display-7">Happy Clients</p>


                  </div>
              </div>
          </div>
          <div class="card col-12 col-md-6 col-lg-4">
              <div class="card-wrapper">
                  <div class="card-box align-left">

                      <h5 class="card-title mbr-fonts-style display-2"><strong>76 +</strong></h5>
                      <p class="card-text mbr-fonts-style display-7">Brands</p>

                  </div>
              </div>
          </div>
          <div class="card col-12 col-md-6 col-lg-4">
              <div class="card-wrapper">
                  <div class="card-box align-left">

                      <h5 class="card-title mbr-fonts-style display-2"><strong>25 +</strong></h5>
                      <p class="card-text mbr-fonts-style display-7">Brand Partners
                      </p>

                  </div>
              </div>
          </div>
          <div class="card col-12 col-md-6 col-lg-4">
              <div class="card-wrapper">
                  <div class="card-box align-left">

                      <h5 class="card-title mbr-fonts-style display-2"><strong>20 +</strong></h5>
                      <p class="card-text mbr-fonts-style display-7">Active Brand Client
                      </p>

                  </div>
              </div>
          </div>
          <div class="card col-12 col-md-6 col-lg-4">
              <div class="card-wrapper">
                  <div class="card-box align-left">

                      <h5 class="card-title mbr-fonts-style display-2"><strong>400 +</strong></h5>
                      <p class="card-text mbr-fonts-style display-7">Professional Staff
                      </p>

                  </div>
              </div>
          </div>
          <div class="card col-12 col-md-6 col-lg-4">
              <div class="card-wrapper">
                  <div class="card-box align-left">

                      <h5 class="card-title mbr-fonts-style display-2"><strong>8 + </strong></h5>
                      <p class="card-text mbr-fonts-style display-7">Years of experience in Gift-Cards
                      </p>

                  </div>
              </div>
          </div>
      </div>
  </div>
</section>
<!-- slider section -->
<section data-bs-version="5" class="numbers1 cid-sz56uYA5zF" id="numbers01-a">
    <div class="container">

        <div class="col-12 m-auto col-lg-8 pb-5">
            <h3 class="mbr-section-title mbr-fonts-style align-left mb-0 display-7">OUR FEATURES</h3>
            <h5 class="mbr-section-subtitle mbr-fonts-style align-left mb-0 mt-2 display-5"><strong>We Are CredenceRewards.</strong></h5>
        </div>
    <div class="row">
      <div class="col-md-6 ">
        <div class="img-box">
          <img src="{% static 'assets/images/cr-images/egift_card-au.png' %}">
        </div>
      </div>
      <div class="col-md-6">
        <div class="detail-box">
          <div class="heading_container">
            <h2>
              We Are CredenceRewards
            </h2>
          </div>
          <p class="display-7">
            We believe that there’s a perfect gift for everyone, 
            which is why we offer you gift cards from 100+ reputed brands for
             every gifting occasion. Gift your loved ones the freedom of choice to 
             select a product they truly desire.<br>
             For your last-minute gifting needs, we have e-gift cards from the
              leading brands in the country. Gift cards and e-gift cards also give the
               recipients the freedom to shop at an outlet close to their home or office.
                Experience new-age gifting with Credence Rewards - India's most powerful 
                gifting platform.

          </p>
          <a href="">
            Read More
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- client section -->
<section data-bs-version="5" class="clients2 cid-sz583xO0z3" id="clients02-d">
    
    <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(255, 255, 255);">
    </div>
    <div class="images-container container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title text-white mbr-fonts-style align-center mb-2 display-7">
                <span class="bg-secondary p-2">What Our Customers Say</span></h3>
            <h4 class="mbr-section-subtitle mbr-fonts-style align-center pb-4 display-5"><strong class="text-primary bg-info">We love to work with our clients</strong>
            </h4>

        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-3 col-md-4">
                <div class="card-wrapper">
                <p class="text-success font-weight-bold text-center">Widest choice <br> for the sender<p>
                    <img src="{% static 'assets/images/cr-images/login-pic.jpg' %}">
                    
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="card-wrapper">
            <p class="text-success text-center font-weight-bold">Unlimited choice <br> for the recipient<p>
              <img src="{% static 'assets/images/cr-images/login-pic.jpg' %}">
                    
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="card-wrapper">
                            <p class="text-success text-center font-weight-bold">Multiple Brands <br>Choices<p>
                    <img src="{% static 'assets/images/cr-images/login-pic.jpg' %}">
                </div>
            </div>
            
        </div>
    </div>
</section>




{% endblock %}

templates/frontend/base.html
{% load static %}
{% load static %}

<!DOCTYPE html>
<html>

<!-- Mirrored from mobirise.com/extensions/glassm5/corporate/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 17 Aug 2022 09:49:15 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="{% static 'assets/images/cr-images/favicon.png' %}" type="image/x-icon">
    <meta name="description" content="GlassM5 Theme Live Demo Site">


    <title>CredenceRewards | Buy Gift Cards</title>
    <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/recaptcha.css' %}">
    <link rel="preload"
        href="https://fonts.googleapis.com/css?family=Lexend:100,300,400,500,600,700,800&amp;display=swap" as="style"
        onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Lexend:100,300,400,500,600,700,800&amp;display=swap">
    </noscript>
    <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}">
    <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">


    <!-- Google Tag Manager-->
    <script>(function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'http://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-PFK425');</script>
    <!-- End Google Tag Manager -->


</head>

<body>
<!-- The actual snackbar -->
<div id="snackbar"></div>
    <!-- Google Tag Manager-->
    <noscript><iframe src="http://www.googletagmanager.com/ns.html?id=GTM-PFK425" height="0" width="0"
            style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager -->

    <section data-bs-version="5" class="menu menu1 cid-sz55TXuY2C" once="menu" id="menu1-1">

        <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
            <div class="container-fluid">
                <div class="navbar-brand">

                    <span class="navbar-caption-wrap"><a class="navbar-caption display-5"
                            href="{% url 'frontend:index' %}"style="color:#f3cf17;">CredenceRewards</a>
                            {% comment %} <a class="navbar-brand" href="#">
                                <img src="{% static 'assets/images/cr-images/crlogo-tm.png' %}" alt="..." height="36">
                                </a> {% endcomment %}
                            </span>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                    data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <div class="hamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                        <li class="nav-item"><a class="nav-link link text-success display-7" href="{% url 'frontend:index' %}"
                                aria-expanded="false">
                                Home</a></li>
                        <li class="nav-item"><a class="nav-link link text-success display-7" href="{% url 'frontend:about_us_page' %}"
                                aria-expanded="false">
                                About us</a></li>
                        <li class="nav-item"><a class="nav-link link text-success display-7" href="{% url 'frontend:services_page' %}">
                                Services</a></li>
                        <li class="nav-item"><a class="nav-link link text-success display-7" href="{% url 'frontend:gift_cards' %}">
                                Gift Cards</a></li>
                                
                        <li class="nav-item"><a class="nav-link link text-success display-7" href="{% url 'frontend:contact_us_page' %}">
                        Contacts</a>
                        </li>
                    </ul>

                    <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-primary display-4" href="{% url 'accounts:login' %}">
                            Get Started</a></div>
                </div>
            </div>
        </nav>
    </section>
    
{% block content %}
{% endblock %}
        <div id="snackbar" class="show-error">
          <!-- <p class="show-error"></p> -->
      
        </div>
    <section data-bs-version="5" class="contacts8 cid-sz59VlvkYW" id="contacts08-f">


        <div class="container">
            <div class="row mbr-white">
                <div class="col-12 col-md-6 col-lg-5">
                    <div class="wrapper">
                        <h5 class="mbr-section-subtitle mbr-fonts-style mb-2 display-4">CALL US</h5>
                        <p class="phone mbr-fonts-style mb-4 display-5"><strong>
                                +91 9920950509
                            </strong></p>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <h5 class="mbr-section-subtitle mbr-fonts-style mb-2 display-4">VISIT US</h5>
                    <ul class="list mbr-fonts-style display-4">
                        <li class="mbr-text item-wrap">Laxmi Shoppe Shop No. 3,
                    <br>Opposite Neem Chhaya,
                    <br>Below Ramji Ashar School,<br>M.G. Road, Ghatkopar - (East),
                    <br>Mumbai - 400077,<br>India
                        </li>
                        <li class="mbr-text item-wrap">info@credencerewards.com</li>
                    </ul>
                </div>
                <div class="col-12 col-md-12 col-lg-3">
                    <div class="social-row display-7">
                        <div class="soc-item">
                            <a href="https://www.facebook.com/Credencerewards/" target="_blank">
                                <span class="mbr-iconfont socicon-facebook socicon"></span>
                            </a>
                        </div>
                        <div class="soc-item">
                            <a href="https://www.linkedin.com/company/credencerewards/?originalSubdomain=in" target="_blank">
                                <span class="mbr-iconfont socicon-linkedin socicon"></span>
                            </a>
                        </div>
                        <div class="soc-item">
                            <a href="https://www.instagram.com/credencerewards/" target="_blank">
                                <span class="mbr-iconfont socicon-instagram socicon"></span>
                            </a>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </section>
    <section data-bs-version="5" class="footer1 cid-sz56sBQ95d" once="footers" id="footer02-9">



        <div class="container">
            <div class="row mbr-white">
                <div class="col-12 col-md-6 col-lg-6">
                    <div class="wrapper">
                        <h5 class="mbr-section-subtitle mbr-fonts-style mb-2 display-7">
                            <strong>About Us</strong>
                        </h5>
                        <p class="mbr-text mbr-fonts-style mb-4 display-4">
                            We believe that there’s a perfect gift for everyone, which is why we offer you gift cards from 100+ reputed brands for every gifting occasion. Gift your loved ones the freedom of choice to select a product they truly desire.

For your last-minute gifting needs, we have e-gift cards from the leading brands in the country. Gift cards and e-gift cards also give the recipients the freedom to shop at an outlet close to their home or office. Experience new-age gifting with Credence Rewards - India's most powerful gifting platform.
                        </p>


                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    <h5 class="mbr-section-subtitle mbr-fonts-style mb-2 display-7">
                        <strong>Company</strong>
                    </h5>
                    <ul class="list mbr-fonts-style display-4">
                        <li class="mbr-text item-wrap"><a href="{% url 'frontend:about_us_page' %}" class="text-white">About</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Jobs</a></li>
                        <li class="mbr-text item-wrap"><a href="{% url 'frontend:contact_us_page' %}" class="text-white">Contacts</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Support</a></li>
                    </ul>
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    <h5 class="mbr-section-subtitle mbr-fonts-style mb-2 display-7">
                        <strong>Themes</strong>
                    </h5>
                    <ul class="list mbr-fonts-style display-4">

                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Features</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Team</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Vouchers</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Info</a></li>
                    </ul>
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    <h5 class="mbr-section-subtitle mbr-fonts-style mb-2 display-7">
                        <strong>Support</strong>
                    </h5>
                    <ul class="list mbr-fonts-style display-4">
                        <li class="mbr-text item-wrap"><a href="{% url 'frontend:contact_us_page' %}" class="text-white">Contacts</a></li>
                        <li class="mbr-text item-wrap"><a href="{% url 'frontend:about_us_page' %}" class="text-white">About Us</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Terms of Service</a></li>
                        <li class="mbr-text item-wrap"><a href="#" class="text-white">Cancellation</a></li>
                    </ul>
                </div>


            </div>
        </div>
    </section>

    <script>
      // show alert message for notification
  
      function showSnackbar() {
        var snackBar =
          document.getElementById("snackbar")
        snackBar.className = "show-bar";
  
        setTimeout(function () {
          snackBar.className =
            snackBar.className.replace("show-bar", "show-error");
        }, 5000);
      }
  
    </script>
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == "error" %}
    <script>
      showSnackbar();
      $('#snackbar').css("cssText", "background-color: red !important;");
      $('#snackbar').text("{{ message }}");
    </script>
    {% else %}
    <script>
      showSnackbar();
      $('#snackbar').css("cssText", "background-color: green !important;");
      $('#snackbar').text("{{ message }}");
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}

    <script src="{% static 'assets/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
    <script src="{% static 'assets/ytplayer/index.js' %}"></script>
    <script src="{% static 'assets/playervimeo/vimeo_player.js' %}"></script>
    <script src="{% static 'assets/mbr-switch-arrow/mbr-switch-arrow.js' %}"></script>
    <script src="{% static 'assets/theme/js/script.js' %}"></script>
    <script src="{% static 'assets/formoid/formoid.min.js' %}"></script>




</body>

<!-- Mirrored from mobirise.com/extensions/glassm5/corporate/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 17 Aug 2022 09:49:39 GMT -->

</html>